### ISSUE TITLE
Quadric vs Quadratic

### ISSUE THREAD

**Issue by amirebrahimi** [Whinarn/MeshDecimator#1]
Minor, but I think you meant to call this class `FastQuadricMeshSimplification`, no?

https://github.com/Whinarn/MeshDecimator/blob/707ffc5c77bacbc99cda1ba01127e8d53092af21/MeshDecimator/Algorithms/FastQuadraticMeshSimplification.cs#L50

**Comment by Whinarn** [comment]
Ah, yes. You are correct.

I will resolve this in a few hours. Thank you.

**Comment by Whinarn** [comment]
This has now been resolved with a breaking change. Thanks again!

**Comment by amirebrahimi** [comment]
Thanks! FYI - DLLs weren't regenerated for the Unity example. Not sure if that matters though in relation to #3

**Comment by Whinarn** [comment]
Yet again you are correct, I totally missed that part.

I also stumbled upon another silly thing, which was that the meta files for the Unity example project was being ignored by the .gitignore I had for the VisualStudio project in the root directory. So I resolved that as well. I cannot believe that I missed that.
