### ISSUE TITLE
Error in decimation of flat plane

### ISSUE THREAD

**Issue by HonestHobbit** [Whinarn/MeshDecimator#17]
Sorry to trouble you but I've been doing some testing with your library. I've been using its lossless methods and they seem to hold up great when working with fully enclosed solids, but given a flat plane with no enclosing sides or bottom it cuts a corner off. It's a 16 by 16 subdivided plane I made in blender. The same object with sides and bottom decimates just fine. Can this be fixed or is this algorithm not meant to be applied to non-enclosed solid objects?
Here are the example files;
[planes.zip](https://github.com/Whinarn/MeshDecimator/files/3692847/planes.zip)

**Comment by Whinarn** [comment]
Hi, @LyingDwarf!

I am aware of this issue.
Please see my comment for a similar issue reported in my other project using the same mesh simplification algorithm: https://github.com/Whinarn/UnityMeshSimplifier/issues/16#issuecomment-513567244

In short, the algorithm in its current shape isn't very well suited for this. It could most definitely be improved, but I won't be implementing support to deal with planes similar to your needs. Sorry for the inconvenience.

If you manage to get a working solution, I do accept pull requests however.

Thanks!

**Comment by HonestHobbit** [comment]
Thanks for the quick response. Since the lossless methods seem to work very well on enclosed solids I may be able to work around the issue by generating fully enclosed solids, simplifying using the lossless methods, and then discarding the extra sides that I don't need.

**Comment by Whinarn** [comment]
Closing this issue because the project is being archived. Consider using [UnityMeshSimplifier](https://github.com/Whinarn/UnityMeshSimplifier) instead, if you are using Unity.
