### ISSUE TITLE
Subrepo?

### ISSUE THREAD

**Issue by amirebrahimi** [Whinarn/MeshDecimator#3]
I've added support for MeshDecimator to [AutoLOD](https://github.com/Unity-Technologies/AutoLOD/commit/35d4110e2e1b54d6349e8d8df2bd1b5b2fd3eb16). It's possible we could make it the default LOD generator for now if I subrepo your project. However, your project isn't currently set up for that.

If you could split off the subtree for the https://github.com/Whinarn/MeshDecimator/tree/master/UnityExample/Assets/Plugins/MeshDecimator, then I could subrepo that into AutoLOD under the Packages folder and you could also subrepo it back into this repo.

What do you think?

**Comment by Whinarn** [comment]
I will think about this. Let me get back to you on this in a few hours as well.
Thanks for showing an interest!

**Comment by Whinarn** [comment]
@amirebrahimi 
I have created a new repository that I believe should work a lot better for you, directly adjusted for Unity (no extra vector conversions necessary) and without the need of a DLL file.

The new repository and project can be found here: https://github.com/Whinarn/UnityMeshSimplifier
I hope this works better for you.

Please tell me if this was not what you had in mind. Thanks!

**Comment by amirebrahimi** [comment]
I wasn't implying that you had to rework it for Unity alone because it's common that each simplifier has it's own separate data format. However, thank you for doing this work. I can certainly make use of this project, but was thinking that it might be harder to maintain long-term, no?

**Comment by Whinarn** [comment]
Yes, I know that you weren't implying that I rework it for Unity alone. I meant if the structure of the project worked better for you.

It certainly adds a few steps in maintaining that one algorithm (Fast Quadric Mesh Simplification). But the idea was that MeshDecimator would be a library for .NET where different mesh simplification/decimation algorithms could be used easily towards the same API with some extra features, meanwhile UnityMeshSimplifier is just one mesh simplification algorithm easily used directly from Unity.

But I didn't really like the idea of just having the MeshDecimator DLL along with some extra scripts for Unity in a separate repository, so I ended up creating UnityMeshSimplifier instead. But I plan to maintain both, while only focusing on the on the one algorithm (Fast Quadric Mesh Simplification) for UnityMeshSimplifier.

**Comment by amirebrahimi** [comment]
Thank you for the clarification. I'm actually going to keep support for MeshDecimator as a separate simplifier in case more gets added there and now, UnityMeshSimplifier is the [default simplifier](https://github.com/Unity-Technologies/AutoLOD/commit/6e692268003def7182907f49f28b5cb53befc847) in AutoLOD.
