### ISSUE TITLE
Saving MeshObj does not work on non US-machines

### ISSUE THREAD

**Issue by goitrodos** [Whinarn/MeshDecimator#4]
When writing floats to a file make sure to use the CultureInfo.InvariantCulture. Your code won't work for most European culture sets.

Change in ObjMesh.WriteFile all occurences of

writer.Write(vertex.[xyz].ToString("g"));

to e.g.

writer.Write(vertex.x.ToString("g", CultureInfo.InvariantCulture));

Kind Regards!

**Comment by Whinarn** [comment]
Wow, I cannot believe I missed that. I'm Swedish myself so I know very well about the problem you are referring to.

Thank you for reporting this!

**Comment by Whinarn** [comment]
This has now been resolved. Thank you again!
