### ISSUE TITLE
OBJ Mesh Texture Coordinates and Normals

### ISSUE THREAD

**Issue by Whinarn** [Whinarn/MeshDecimator#6]
Add support for reading and writing texture coordinates and normals with OBJ meshes.

**Comment by Whinarn** [comment]
Added support for reading and writing texture coordinates and normals: https://github.com/Whinarn/MeshDecimator/commit/58fd859b5b23470269499a9fe4f63e356466317d
Added support for texture coordinates and normals with the Mesh Decimator Tool: https://github.com/Whinarn/MeshDecimator/commit/a8c49962fddd305f6aeb0ae007daa3cb5510ae8a

Needs more testing.

**Comment by hanaimin** [comment]
good job

**Comment by Whinarn** [comment]
This has now been merged into master in commit https://github.com/Whinarn/MeshDecimator/commit/fe2ce7519f060dcd7af798f59d951fa5f0a5ad83.
